version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Europe/Paris'
    commit-message:
      prefix: 'ci'
      include: 'scope'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '07:00'
      timezone: 'Europe/Paris'
    commit-message:
      prefix: 'build'
      include: 'scope'
