baseURL: "https://frenchvandal.cn/"
title: Miscellanies
author: frenchvandal
summaries: true
languageCode: en-us
pygmentsCodeFences: true
enableRobotsTXT: true
theme: hugo-flex
publishDir: public
enableGitInfo: true
copyright: >
  Copyright © 2021 frenchvandal – Except where otherwise noted, content on this
  site is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives
  4.0 International License (https://creativecommons.org/licenses/by-nc-nd/4.0/).

permalinks:
  posts: "/:filename/"
  pages: "/:filename/"

params:
  color: rgb(18,18,18)
  width: 47rem
  description: Cool stories of my life
  footer: <a href="/sitemap/">Sitemap</a>
  rss: >
    To subscribe to this RSS feed, copy the address in the address bar and paste
    it into your favorite feed reader.
  divider: '\2015\2015'
  schema: true
  opengraph: false
  twittercards: false
  summaries: true
  enableEmoji: true

outputFormats:
  json:
    baseName: "index"
    mediaType: "application/json"
    isPlainText: true

outputs:
  home:
    - html
    - rss
    - json

menu:
  nav:
    - name: Tags
      url: tags/
      weight: 1
    - name: Categories
      url: categories/
      weight: 2
    - name: About
      url: about/
      weight: 3
