name: Deploy Hugo on GitHub Pages
on:
  push:
    branches: master

env:
  HUGO_VERSION: 0.80.0
  HUGO_UGLYURLS: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@v2.1.0
        with:
          overall_threshold: critical
          pages_threshold: major_outage

      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/hugo/**
          key: ${{ runner.os }}-hugo

      - name: Test cache
        run: |
          echo "Cache: ${{ steps.cache.outputs.cache-hit }}"

      - name: Hugo
        uses: crazy-max/ghaction-hugo@v1.3.3
        with:
          version: latest
          extended: false
          args: --destination /tmp/hugo/ --minify --disableKinds RSS

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: |
           gsutil -h "Cache-Control:public,max-age=86400,must-revalidate" -m rsync -r -d -j css,html,js,svg,txt,webmanifest /tmp/hugo/ gs://frenchvandal
           gsutil -m setmeta -h "Content-Type: text/html; charset=utf-8" -h "Content-Language: en" gs://frenchvandal/**/*.html
