name: Deploy Hugo on GitHub Pages
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Hugo
        uses: crazy-max/ghaction-hugo@v1.3.3
        with:
          version: latest
          extended: false
          args: --minify --disableKinds RSS

      - name: Aliyuncli
        uses: jerray/setup-aliyun-cli-action@master
        with:
          aliyun-cli-version: '3.0.66'
          mode: AK
          region: ${{ secrets.OSS_REGION }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - run: |
          aliyun oss cp $GITHUB_WORKSPACE/public/ oss://normcore/ -r -f -u --parallel 5
          aliyun cdn RefreshObjectCaches --ObjectType Directory --ObjectPath https://frenchvandal.cn/
          aliyun cdn PushObjectCache --ObjectPath https://frenchvandal.cn/
