name: Deploy Hugo on GitHub Pages
on:
  push:
    branches: master

env:
  HUGO_VERSION: 0.79.0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@v2.0.1
        with:
          overall_threshold: critical
          pages_threshold: major_outage

      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Hugo
        uses: crazy-max/ghaction-hugo@v1.3.3
        with:
          version: latest
          extended: false
          args: --cleanDestinationDir --enableGitInfo --gc --minify --disableKinds RSS

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          external_repository: frenchvandal/frenchvandal.github.io
          publish_branch: master
          publish_dir: ./public
