name: Deploy Hugo on Google Cloud Storage

on:
  push:
    branches: master

env:
  HUGO_VERSION: 0.72.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Download Hugo
        run: sudo wget -q https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb

      - name: Install Hugo
        run: sudo dpkg -i hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb

      - name: Build Hugo
        run: hugo --cleanDestinationDir --enableGitInfo --gc --minify --disableKinds RSS

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gsutil -m rsync -r -d public gs://frenchvandal
