name: Deploy Hugo on GitHub Pages
on:
  push:
    branches: master

env:
  HUGO_VERSION: 0.79.0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check GitHub Pages status
        run: |
          GH_PAGES_STATUS=$(curl -s -X GET -H "Header:Value" https://kctbh9vrtdwd.statuspage.io/api/v2/components.json | jq -r '.components[] | select(.name == "GitHub Pages") | .status')

      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Install Hugo
        run: |
          wget -q $GITHUB_SERVER_URL/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb -P ~
          sudo apt-get -qq install ~/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb > /dev/null

      - name: Build and deploy
        run: |
          COMMIT_SHA=$(cut -c-7 <<< "$GITHUB_SHA")
          git config --global user.email "$(git log --format='%ae' HEAD^!)"
          git config --global user.name "$(git log --format='%an' HEAD^!)"
          git submodule update --remote --rebase
          mkdir -p $GITHUB_WORKSPACE/public
          git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git $GITHUB_WORKSPACE/public
          hugo --cleanDestinationDir --enableGitInfo --gc --minify --disableKinds RSS
          cd $GITHUB_WORKSPACE/public
          git add .
          git commit -m "Update from $GITHUB_REPOSITORY@$COMMIT_SHA"
          git push origin master
          curl -u $GITHUB_ACTOR:${{ secrets.PERSONAL_ACCESS_TOKEN }} -s -X POST --data '{"event_type": "deploy_hugo_update"}' -H "Accept: application/vnd.github.v3+json" $GITHUB_API_URL/$GITHUB_ACTOR/$GITHUB_ACTOR.github.io/dispatches
