name: Deploy Hugo on Google Cloud Storage

on:
  push:
    branches: master

env:
  HUGO_VERSION: 0.78.2

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Download and install Hugo
        run: |
          sudo wget -q https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb
          sudo dpkg -i hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb
          ls $GITHUB_WORKSPACE/public

      - name: Build Hugo
        run: hugo --cleanDestinationDir --enableGitInfo --gc --minify --disableKinds RSS

      - name: Check stuff
        run: |
          COMMIT_SHA=$(cut -c-7 <<< "$GITHUB_SHA")
          ls $GITHUB_WORKSPACE/public
          echo "commit_sha : $COMMIT_SHA"
          echo "CI : $CI"
          echo "GITHUB_WORKFLOW : $GITHUB_WORKFLOW"
          echo "GITHUB_RUN_ID : $GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER : $GITHUB_RUN_NUMBER"
          echo "GITHUB_ACTION : $GITHUB_ACTION"
          echo "GITHUB_ACTIONS : $GITHUB_ACTIONS"
          echo "GITHUB_ACTOR : $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY : $GITHUB_REPOSITORY"
          echo "GITHUB_EVENT_NAME : $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH : $GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE : $GITHUB_WORKSPACE"
          echo "GITHUB_SHA : $GITHUB_SHA"
          echo "GITHUB_REF : $GITHUB_REF"
          echo "GITHUB_SERVER_URL : $GITHUB_SERVER_URL"
          echo "GITHUB_API_URL : $GITHUB_API_URL"
          echo "GITHUB_GRAPHQL_URL : $GITHUB_GRAPHQL_URL"

      - name: commit PUBLIC
        run: |
          git submodule update --remote --rebase
          git add .
          git commit -m "update $COMMIT_SHA"
          git push origin master
