name: Deploy Hugo on Aliyun OSS
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.80.0

      - name: Set up Hugo
        uses: frenchvandal/ghaction-hugo@v1.3.3
        with:
          version: v0.80.0
          extended: false
          args: --minify --disableKinds RSS

      - name: Test
        run: |
          aliyun configure set --mode AK --region ${{ secrets.OSS_REGION }} --access-key-id ${{ secrets.OSS_ACCESS_KEY_ID }} --access-key-secret ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          aliyun help
          aliyun oss cp ./public/ oss://${{ secrets.OSS_BUCKET }}/ -r -f -u -j 10

      - name: Upload Hugo artifacts to OSS bucket
        run: aliyun oss cp ./public/ oss://${{ secrets.OSS_BUCKET }}/ -r -f -u -j 10
