name: Deploy Hugo on GitHub Pages
on:
  push:
    branches: master

env:
  HUGO_VERSION: 0.79.0

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check GitHub Pages status
        run: |
          GH_PAGES_STATUS=$( curl -s  -X GET -H "Header:Value" https://kctbh9vrtdwd.statuspage.io/api/v2/components.json |  jq -r '.components[] | select(.name == "GitHub Pages") | .status' )
          echo ${GH_PAGES_STATUS}

      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: true

      - name: Download and install Hugo
        run: |
          sudo wget -q https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb
          sudo dpkg -i hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb

      - name: Build and deploy
        run: |
          export COMMIT_SHA=$(cut -c-7 <<< "$GITHUB_SHA")
          git config --global user.email "octocat@users.noreply.github.com"
          git config --global user.name "The Octocat"
          git submodule update --remote --rebase
          mkdir -p $GITHUB_WORKSPACE/public
          git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git $GITHUB_WORKSPACE/public/
          hugo --cleanDestinationDir --enableGitInfo --gc --minify --disableKinds RSS
          cd $GITHUB_WORKSPACE/public
          git add .
          git commit -m "Update from $GITHUB_REPOSITORY@$COMMIT_SHA"
          git push origin master
