name: Deploy Hugo on Aliyun OSS
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Aliyun Configure
        run: aliyun configure set --mode AK --region ${{ secrets.OSS_REGION }} --access-key-id ${{ secrets.OSS_ACCESS_KEY_ID }} --access-key-secret ${{ secrets.OSS_ACCESS_KEY_SECRET }} --language zh

      - name: Hugo
        uses: frenchvandal/ghaction-hugo@master
        with:
          version: latest
          extended: false
          args: --minify --disableKinds RSS

      - name: Aliyun OSS
        run: |
          aliyun oss cp ./public/ oss://${{ secrets.OSS_BUCKET }}/ -r -f -u -j 10
