name: Deploy Hugo on GitHub Pages
on:
  push:
    branches: master

env:
  HUGO_VERSION: 0.79.0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check GitHub Pages status
        run: |
          GH_PAGES_STATUS=$(curl -s -X GET -H "Header:Value" https://kctbh9vrtdwd.statuspage.io/api/v2/components.json | jq -r '.components[] | select(.name == "GitHub Pages") | .status')

      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Install Hugo
        run: |
          wget -q $GITHUB_SERVER_URL/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb -P ~
          sudo apt-get -qq install ~/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb > /dev/null

      - name: Build and deploy
        run: |
          COMMIT_SHA=$(cut -c-7 <<< "$GITHUB_SHA")
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git submodule update --remote --rebase
          hugo --destination ./docs --cleanDestinationDir --enableGitInfo --gc --minify --disableKinds RSS
          git add .
          git commit -m "Update Hugo content from $COMMIT_SHA"
          git push origin master
