name: Deploy Hugo on Aliyun OSS
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Hugo
        uses: frenchvandal/ghaction-hugo@v1.3.3
        with:
          version: v0.80.0
          extended: false
          args: --minify --disableKinds RSS

      - name: Aliyuncli
        uses: jerray/setup-aliyun-cli-action@master
        with:
          aliyun-cli-version: 3.0.69
          mode: AK
          region: ${{ secrets.OSS_REGION }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - run: |
          ls -Rd $GITHUB_WORKSPACE/public/*
          aliyun oss cp ./public/ oss://${{ secrets.OSS_BUCKET }}/ -r -f -u -j 10 --loglevel info
          cat $GITHUB_WORKSPACE/ossutil.log
