name: Deploy Hugo on GitHub Pages
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Hugo
        uses: frenchvandal/ghaction-hugo@v1.3.4
        with:
          version: v0.80.0
          extended: false
          args: --minify --disableKinds RSS

      - name: Aliyuncli
        uses: jerray/setup-aliyun-cli-action@master
        with:
          aliyun-cli-version: '3.0.66'
          mode: AK
          region: ${{ secrets.OSS_REGION }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - run: |
          aliyun oss cp ./public/ oss://${{ secrets.OSS_BUCKET }}/ -r -f -u --parallel 5
          aliyun cdn RefreshObjectCaches --ObjectType Directory --ObjectPath https://frenchvandal.cn/
          aliyun cdn RefreshObjectCaches --ObjectType Directory --ObjectPath https://frenchvandal.cn/about/
          aliyun cdn RefreshObjectCaches --ObjectType Directory --ObjectPath https://frenchvandal.cn/archives/
          aliyun cdn RefreshObjectCaches --ObjectType Directory --ObjectPath https://frenchvandal.cn/css/
          aliyun cdn RefreshObjectCaches --ObjectType Directory --ObjectPath https://frenchvandal.cn/pages/
          aliyun cdn RefreshObjectCaches --ObjectType Directory --ObjectPath https://frenchvandal.cn/tags/
          aliyun cdn PushObjectCache --ObjectPath https://frenchvandal.cn/index.html
          aliyun cdn PushObjectCache --ObjectPath https://frenchvandal.cn/about/index.html
          aliyun cdn PushObjectCache --ObjectPath https://frenchvandal.cn/archives/index.html
          aliyun cdn PushObjectCache --ObjectPath https://frenchvandal.cn/pages/index.html
          aliyun cdn PushObjectCache --ObjectPath https://frenchvandal.cn/tags/index.html
