name: Deploy Hugo on Aliyun OSS
on:
  push:
    branches: master
    paths:
      - 'content/**'
      - 'static/**'
      - '.github/workflows/deployment.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Insant & Run Hugo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: frenchvandal/action-hugo@master
        with:
          version: latest
          extended: false
          args: --cleanDestinationDir --minify --disableKinds RSS
