name: Deploy Hugo on Aliyun OSS
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.80.0
      - name: Create Hugo artefacts
        run: hugo

      - name: Set up Hugo
        uses: frenchvandal/ghaction-hugo@v1.3.3
        with:
          version: latest
          extended: false
          args: --minify --disableKinds RSS

      - name: Upload Hugo artifacts to OSS bucket
        run: |
          aliyun configure set --mode AK --region ${{ secrets.OSS_REGION }} --access-key-id ${{ secrets.OSS_ACCESS_KEY_ID }} --access-key-secret ${{ secrets.OSS_ACCESS_KEY_SECRET }} --language zh
          aliyun oss cp ./public/ oss://${{ secrets.OSS_BUCKET }}/ -r -f -u -j 10

      - name: Upload to oss
        uses: yinlinyang/ali-oss-utils@v1.0.10
        with:
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          region: ${{ secrets.OSS_REGION }}
          bucket: ${{ secrets.OSS_BUCKET }}
          source: ./public
          target: /
